[package]
name = "rabai"
version = "0.1.0"
edition = "2021"

[dependencies]
shellfn = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }

